language: php
jobs:
  include:
    - php: 7.4
      env: M2_VERSION=2.4.2
    - php: 7.4
      env: M2_VERSION=2.4.1-p1
      before_script: composer self-update --1
    - php: 7.4
      env: M2_VERSION=2.4.0-p1
    - php: 7.3
      env: M2_VERSION=2.4.2
    - php: 7.3
      env: M2_VERSION=2.4.1-p1
    - php: 7.3
      env: M2_VERSION=2.4.0-p1
    - php: 7.3
      env: M2_VERSION=2.3.6-p1
    - php: 7.3
      env: M2_VERSION=2.3.5
    - php: 7.3
      env: M2_VERSION=2.3.4
    - php: 7.3
      env: M2_VERSION=2.3.3
cache:
  directories:
    - $HOME/.composer/cache
script:
  - dev/ci/build.sh
