language: php
php:
  - 7.1
  - 7.0
  - 5.6
env:
  - M2_VERSION=2.2.2
  - M2_VERSION=2.1.11
  - M2_VERSION=2.0.17
matrix:
  include:
    - php: 5.5
      env: M2_VERSION=2.0.16
  exclude:
    - php: 5.6
      env: M2_VERSION=2.2.2
cache:
  directories:
    - $HOME/.composer/cache
script:
  - dev/ci/build.sh
