language: php
php:
  - 7.4
  - 7.3
env:
  - M2_VERSION=2.4.2
  - M2_VERSION=2.4.1
  - M2_VERSION=2.4.0
jobs:
  include:
    - php: 7.3
      env: M2_VERSION=2.3.6-p1
    - php: 7.3
      env: M2_VERSION=2.3.5
cache:
  directories:
    - $HOME/.composer/cache
script:
  - dev/ci/build.sh
